### ISSUE TITLE
All 4 tiles blinking simultaneously after resetting.

### ISSUE THREAD

**Issue by ultron1101** [ultron1101/Memory-Game#1]
After losing a round. Pressing any key leads to the resetting of the game and consequently all the 4 tiles blinking together. After resetting the game only one tile should blink indicating which tile to click to start the game.

**Comment by IrfanSalim** [comment]
Hey, I would like to take this up

**Comment by ultron1101** [comment]
Sure! Go ahead.

**Comment by ultron1101** [comment]
> Hey, I would like to take this up

Sure! Go ahead.
